# Generated by Django 4.1 on 2023-08-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
    ]
