# Generated by Django 4.1 on 2023-08-22 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_person_user_alter_person_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ManyToManyField(to='api.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='BirthDate',
            field=models.DateField(default=datetime.date(2005, 8, 22)),
        ),
    ]
