# Generated by Django 4.1 on 2023-08-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_person_skills_skill_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
