# Generated by Django 4.1 on 2023-08-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AddField(
            model_name='person',
            name='Skills',
            field=models.ManyToManyField(to='api.skill'),
        ),
    ]
