# Generated by Django 4.1 on 2023-08-27 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_person_skills_skill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='Email',
        ),
        migrations.AddField(
            model_name='person',
            name='Skills',
            field=models.ManyToManyField(to='api.skill'),
        ),
        migrations.AlterField(
            model_name='person',
            name='BirthDate',
            field=models.DateField(default=datetime.date(2005, 8, 27)),
        ),
    ]
