# Generated by Django 4.1 on 2023-08-27 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_remove_experience_email_person_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Skills',
        ),
        migrations.AddField(
            model_name='experience',
            name='Email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
