# Generated by Django 4.1 on 2023-08-30 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_person_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfSchool', models.CharField(max_length=30)),
                ('Street', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('CertifiedWith', models.CharField(max_length=20)),
                ('DateFrom', models.DateField(blank=True)),
                ('DateTo', models.DateField(blank=True)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='person_id', to='api.person')),
            ],
        ),
    ]
