# Generated by Django 4.1 on 2023-08-30 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.person'),
        ),
    ]
