# Generated by Django 4.1 on 2023-08-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_education_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='DescribtionOfWork',
            field=models.TextField(default='bla'),
            preserve_default=False,
        ),
    ]
