# Generated by Django 4.1 on 2023-09-16 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_education_dateto_alter_person_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='DateTo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='BirthDate',
            field=models.DateField(default=datetime.date(2005, 9, 16)),
        ),
    ]
